### ISSUE TITLE
Literature higlight hard to read in dark mode

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/reev#407]
**Describe the bug**
PubTator output is highlighted but that is hard to read in dark mode.

**To Reproduce**
1. Go to any gene.
2. Switch to dark mode
3. Scroll to literature section and see issue with highlighting.

**Expected behavior**
Highlight should switch when in dark mode.

**Screenshots**
![image](https://github.com/bihealth/reev/assets/521780/d63c0d0c-efa3-470f-a00e-f6c15094758d)

**Additional context**
N/A

**Comment by gromdimon** [comment]
Hmm, I've fixed this in #402 . Also highlighting appears ok to me (see screenshot).

<img width="1219" alt="Screenshot 2024-01-23 at 12 38 00" src="https://github.com/bihealth/reev/assets/86564271/30b6b4a3-16cd-45eb-99d2-4e9b7c24a3f4">

**Comment by gromdimon** [comment]
@holtgrewe could you provide me more details where exactly the highlighting didn't work out properly?

**Comment by holtgrewe** [comment]
@gromdimon is this live on production?

**Comment by gromdimon** [comment]
> @gromdimon is this live on production?

@holtgrewe Yes, I've just went to https://reev.cubi.bihealth.org/ , toggled dark theme and went to BRCA1.

**Comment by holtgrewe** [comment]
Sorry can still reproduce in both chrome and firefox. Let's look at it together on the same screen when you are around in person next time.
